[package]
name = "from-psql-row"
version = "0.1.0"
edition = "2021"
authors = ["ByteBaker"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "^2.0", features = ["extra-traits"] }
quote = "^1.0"
